{
  description = "nxtermd — terminal multiplexer with proper separation of concerns";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Read version from dist/.version (generated by `make version`).
        # Falls back to git short rev or "dev".
        version =
          if builtins.pathExists ./dist/.version
          then builtins.replaceStrings ["\n"] [""] (builtins.readFile ./dist/.version)
          else if self ? shortRev then self.shortRev
          else if self ? dirtyShortRev then self.dirtyShortRev
          else "dev";

        nxtermd = pkgs.buildGoModule {
          pname = "nxtermd";
          inherit version;
          src = ./.;
          vendorHash = "sha256-e/h3yweXasAeuNuVhIOGUXkuSySvohc+lbjIrNA7O8A=";
          subPackages = [ "server" "frontend" "termctl" ];
          env.CGO_ENABLED = 0;
          ldflags = [ "-s" "-w" "-X main.version=${version}" ];

          # The frontend embeds changelog.txt at compile time.
          preBuild = ''
            echo "${version}: nix build" > frontend/changelog.txt
          '';

          postInstall = ''
            mv $out/bin/server $out/bin/nxtermd
            mv $out/bin/frontend $out/bin/nxterm
            mv $out/bin/termctl $out/bin/nxtermctl
          '';
        };

        mkRpm = dist: pkgs.stdenv.mkDerivation {
          pname = "nxtermd-rpm-${dist}";
          inherit version;
          dontUnpack = true;
          nativeBuildInputs = [ pkgs.nfpm ];

          buildPhase = ''
            # Stage binaries and service file
            cp ${nxtermd}/bin/nxtermd .
            cp ${nxtermd}/bin/nxterm .
            cp ${nxtermd}/bin/nxtermctl .
            cp ${./dist/nxtermd.service} nxtermd.service

            # Read version from the built binary
            export VERSION=$(./nxtermd --version 2>&1 | awk '{print $NF}')
            export GOARCH="${pkgs.go.GOARCH}"
            export DIST=".${dist}"
            ${pkgs.envsubst}/bin/envsubst < ${./dist/nfpm.yaml} > nfpm.yaml

            nfpm package --packager rpm --config nfpm.yaml
          '';

          installPhase = ''
            mkdir -p $out
            cp *.rpm $out/
          '';
        };
      in
      {
        packages.default = nxtermd;

        packages.rpm = pkgs.symlinkJoin {
          name = "nxtermd-rpms-${version}";
          paths = [ (mkRpm "fc43") (mkRpm "el9") ];
        };

        devShells.default = pkgs.mkShell {
          name = "nxtermd-dev";

          packages = with pkgs; [
            bash
            gnumake

            # Server + Frontend + termctl (Go)
            go
            gopls
            gotools  # goimports, etc.
            delve    # Go debugger
            gcc      # C/C++ compiler for cgo

            # Protocol debugging: NDJSON over a Unix socket
            jq
            netcat-gnu  # nc for manual socket interaction

            # Version control
            git

            # Sandbox
            bubblewrap

          ];

          shellHook = ''
            export CLAUDE_CONFIG_DIR=$PWD/.claude-config
            export PATH="$PWD/.local/bin:$PATH"
            export GOPATH="$PWD/.local/go"
            export GOCACHE="$PWD/.local/var/cache/go"
            export NIX_SHELL=nxtermd

            echo
            echo "entering nxtermd dev environment"
            echo "  * go  $(go version)"
            echo "  * gcc $(gcc --version | awk 'NR==1{print $NF}')"
            if [ -z "$IN_SANDBOXED_SHELL" ]; then
              export IN_SANDBOXED_SHELL=1
              exec bwrap \
                --ro-bind / / \
                --bind "$PWD" "$PWD" \
                --bind "/tmp" "/tmp" \
                --dev-bind /dev /dev \
                --proc /proc \
                --unshare-pid \
                --die-with-parent \
                --setenv IN_SANDBOXED_SHELL 1 \
                -- bash -i
            fi
          '';

        };
      }
    );
}
